# Generated by Django 4.1.7 on 2023-03-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact',
        ),
    ]
